import { GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import Footer from "../../components/footer/Footer1";
import BottomHeader1 from "../../components/headers/BottomHeader1";
import MiddleHeader1 from "../../components/headers/MiddleHeader1";
import TopHeader1 from "../../components/headers/TopHeader1";
import Banner1 from "../../components/home/banner/Banner1";
import BreadCrumbBanner from "../../components/shared/Breadcrumb/BreadCrumbBanner";
import Newsletter from "../../components/shared/newsletter/Newsletter1";
import ScrollUpBtn from "../../components/shared/ScrollUpBtn";
import ShoppingCart from "../../components/shoppingCart/ShoppingCart";
import { Product } from "../../types/types";

interface Products {
  products: Product[];
}

const breadcrumbData = [
  { label: "home", value: "/" },
  { label: "cart", value: "/shoppingCart" },
];

const Cart = ({ products }: Products) => {
  return (
    <>
      <Head>
        <title>Cookies Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header className="bg-white">
        {/* =========== top header start ======== */}
        <TopHeader1 />
        {/* =========== top header end ======== */}
        {/* =========== middle header start ======== */}
        <MiddleHeader1 />
        {/* =========== middle header end ======== */}
        {/* =========== bottom header start ======== */}
        <BottomHeader1 />
        {/* =========== bottom header end ======== */}
        {/* =========== banner start ======== */}
        <BreadCrumbBanner breadcrumbData={breadcrumbData} />
        {/* =========== banner end ======== */}
      </header>
      <main className="bg-[#FFFFFF]">
        <section className="max-w-[1200px] pt-16 lg:mx-auto mx-5">
          <ShoppingCart products={products} />
        </section>
        {/* ======== Newsletter start ======= */}
        <section className="mt-[100px]">
          <Newsletter />
        </section>
        {/* ======== Newsletter end ======= */}
        {/* ======== scroll up button start ======= */}
        <ScrollUpBtn />
        {/* ======== scroll up button end ======= */}
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  );
};

export default Cart;

export const getStaticProps: GetStaticProps = async () => {
  // const { data: products } = await axios.get("");
  const res = await fetch("https://cookies-shop.vercel.app/api/products");
  const products = await res.json();
  return {
    props: {
      products,
    },
  };
};
